version: '3.8'

services:
  django:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8888
    environment:
      - DATABASE_HOST=postgres
      - RABBITMQ_HOST=rabbitmq
    ports:
      - 8888:8888
    depends_on:
      - postgres
    volumes:
      - media:/code/media/images
  listener:
    container_name: listener
    restart: on-failure
    build: .
    command: python manage.py uploadlistener
    environment:
      - DATABASE_HOST=postgres
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - media:/code/media/images
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  media: