# Generated by Django 3.1.5 on 2021-01-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210121_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='user',
        ),
    ]
