# Generated by Django 3.1.5 on 2021-01-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20210122_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='placeholder', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
