# Generated by Django 3.1.5 on 2021-01-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='flagged',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_description',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
