# Generated by Django 3.1.5 on 2021-01-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20210127_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_title',
            new_name='title',
        ),
    ]
