# Generated by Django 3.1.5 on 2021-01-29 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20210127_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
