# Generated by Django 3.1.5 on 2021-01-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photo_uu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='uu_id',
            new_name='uuid',
        ),
    ]
