# Generated by Django 3.1.5 on 2021-01-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20210129_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='uuid',
            new_name='uu_id',
        ),
    ]
