# Generated by Django 3.1.5 on 2021-02-23 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20210211_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
