# Generated by Django 3.1.5 on 2021-03-03 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0014_photo_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(related_name='likes', through='photos.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
